
export const actionType = {
    FETCH_ARTICLE : 'FETCH_ARTICLE',
    ADD_ARTICLE : "ADD_ARTICLE",
    DELETE_ARTICLE : "DELETE_ARTICLE",
    UPDATE_ARTICLE : "UPDATE_ARICLE",
    VIEW_ARTICLE : "VIEW_ARTICLE"
}